project: 
  type: website
  output-dir: _site
  execute-dir: project

website: 
  favicon: images/favicon.ico
  page-navigation: true
  title: "A Biomedical Visualization Atlas" 
  site-url: "https://openbiox.github.io/Bizard/" 
  repo-url: https://github.com/openbiox/Bizard
  repo-actions:
    - source
    - issue

  page-footer:
    left: "&copy; CC-By Peng Lab, 2024-2025. All rights reserved."
    right: "This page is built with [Quarto](https://quarto.org/)."
    center: |
      <a href='https://clustrmaps.com/site/1c4xe'  title='Visit tracker'><img src='//clustrmaps.com/map_v2.png?cl=ffffff&w=a&t=n&d=VK6_Uhjas4vA0CDps3EFeB0Fotb8hU50SYT4Fcq5nUI&co=91c5eb&ct=000000'/></a>
    
  sidebar:
    logo: "images/Bizard_logo.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/openbiox/Bizard
        text: "Bizard GitHub website"
      - icon: twitter
        href: https://x.com/PengL_Robin
        text: "Peng Lab Twitter"
      - icon: translate       

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "Graph Gallery"
        href: GraphGallery.qmd
      - section: "𝐁𝐀𝐒𝐈𝐂𝐒"
      - section: "Distribution"
        contents: 
          - text: "Violin Plot"
            href: Distribution/ViolinPlot.qmd
          - text: "Density Plot"
            href: Distribution/Density.qmd
          - text: "Histogram"
            href: Distribution/Histogram.qmd
          - text: "Box Plot"
            href: Distribution/BoxPlot.qmd
          - text: "Ridgeline Plot"
            href: Distribution/Ridgeline.qmd
          - text: "Beeswarm Plot"
            href: Distribution/Beeswarm.qmd
      - section: "Correlation"
        contents: 
          - text: "Scatter Plot"
            href: Correlation/Scatter.qmd
          - text: "Heatmap"
            href: Correlation/Heatmap.qmd
          - text: "Correlogram"
            href: Correlation/Correlogram.qmd
          - text: "Bubble Plot"
            href: Correlation/Bubble.qmd
          - text: "Connected Scatter"
            href: Correlation/ConnectedScatter.qmd
          - text: "2D Density"
            href: Correlation/Density2D.qmd
      - section: "Ranking"
        contents: 
          - text: "Bar Plot"
            href: Ranking/BarPlot.qmd
          - text: "Radar/Spider Chart"
            href: Ranking/Radar.qmd
          - text: "Wordcloud"
            href: Ranking/Wordcloud.qmd
          - text: "Parallel Coordinates Plot"
            href: Ranking/Parallel.qmd
          - text: "Lollipop Plot"
            href: Ranking/Lollipop.qmd
          - text: "Circular Barplot"
            href: Ranking/CircularBarplot.qmd
          - text: "Table"
            href: Ranking/Table.qmd
          - text: "VeenPlot"
            href: Ranking/VennPlot.qmd
          - text: "UpsetPlot"
            href: Ranking/UpsetPlot.qmd
      - section: "Composition/Part Of The Whole"
        contents: 
          - text: "Grouped and Stacked Barplot"
            href: Composition/GroupedBarplot.qmd
          - text: "Treemap"
            href: Composition/Treemap.qmd
          - text: "Donut Chart"
            href: Composition/Donut.qmd
          - text: "Pie Chart"
            href: Composition/PieChart.qmd
          - text: "Dendrogram"
            href: Composition/Dendrogram.qmd
          - text: "Circular Packing Chart"
            href: Composition/CircularPacking.qmd
          - text: "Waffle Chart"
            href: Composition/Waffle.qmd
      - section: "Data Over Time/Evolution"
        contents: 
          - text: "Line Chart"
            href: DataOverTime/LineChart.qmd
          - text: "Area Chart"
            href: DataOverTime/AreaChart.qmd
          - text: "Stacked Area Chart"
            href: DataOverTime/StackedArea.qmd
          - text: "Streamgraph"
            href: DataOverTime/Streamgraph.qmd
          - text: "Timeseries"
            href: DataOverTime/Timeseries.qmd
      - section: "Proportion/Flow"
        contents: 
          - text: "Chord Diagram"
            href: Proportion/ChordDiagram.qmd
          - text: "Network Graph"
            href: Proportion/Network.qmd
          - text: "Sankey Diagram"
            href: Proportion/Sankey.qmd
          - text: "Arc Diagram"
            href: Proportion/ArcDiagram.qmd
          - text: "Hierarchical Edge Bundling"
            href: Proportion/EdgeBundling.qmd
      - text: "ggalign Gallery"
        href: https://yunuuuu.github.io/ggalign-gallery/
      - section: "Animation"
        contents: 
          - text: "Animation"
            href: Animation/Animation.qmd
          - text: "Interactivity"
            href: Animation/Interactivity.qmd
      - section: "𝐎𝐌𝐈𝐂𝐒"
      - section: "𝐂𝐋𝐈𝐍𝐈𝐂𝐒"
      
      - section: "HIPLOT"
        contents: 
          - text: "Area"
            href: Hiplot/001-area.qmd
          - text: "Barcode Plot"
            href: Hiplot/002-barcode-plot.qmd
          - text: "3D Barplot"
            href: Hiplot/003-barplot-3d.qmd
          - text: "Barplot Color Group"
            href: Hiplot/004-barplot-color-group.qmd
          - text: "Barplot (errorbar)"
            href: Hiplot/005-barplot-errorbar.qmd
          - text: "Barplot (errorbar2)"
            href: Hiplot/006-barplot-errorbar2.qmd
          - text: "Barplot Gradient"
            href: Hiplot/008-barplot-gradient.qmd
          - text: "Multiple Barplot&Line"
            href: Hiplot/009-barplot-line-multiple.qmd
          - text: "Barplot"
            href: Hiplot/010-barplot.qmd
          - text: "Beanplot"
            href: Hiplot/011-beanplot.qmd
          - text: "Beeswarm"
            href: Hiplot/012-beeswarm.qmd
          - text: "Corrplot Big Data"
            href: Hiplot/013-big-corrplot.qmd
          - text: "Bivariate Chart"
            href: Hiplot/014-bivariate.qmd   
          - text: "Boxplot"
            href: Hiplot/015-boxplot.qmd
          - text: "Bubble"
            href: Hiplot/016-bubble.qmd
          - text: "Bumpchart"
            href: Hiplot/017-bumpchart.qmd
          - text: "Calibration Curve"
            href: Hiplot/018-calibration-curve.qmd
          - text: "Chi-square-fisher Test"
            href: Hiplot/019-chi-square-fisher.qmd
          - text: "Chord Plot"
            href: Hiplot/020-chord.qmd
          - text: "Circle Packing"
            href: Hiplot/021-circle-packing.qmd
          - text: "Circular Barplot"
            href: Hiplot/023-circular-barplot.qmd
          - text: "Circular Pie Chart"
            href: Hiplot/024-circular-pie-chart.qmd
          - text: "Complex Heatmap"
            href: Hiplot/025-complex-heatmap.qmd
          - text: "Connected Scatterplot"
            href: Hiplot/026-connected-scatterplot.qmd
          - text: "Contour (Matrix)"
            href: Hiplot/027-contour-matrix.qmd
          - text: "Contour (XY)"
            href: Hiplot/028-contour-xy.qmd
          - text: "Simplified Correlation Heatmap"
            href: Hiplot/029-cor-heatmap-simple.qmd
          - text: "Correlation Heatmap"
            href: Hiplot/030-cor-heatmap.qmd
          - text: "Corrplot"
            href: Hiplot/033-corrplot.qmd
          - text: "Custom Heatmap"
            href: Hiplot/034-custom-heat-map.qmd
          - text: "Custom Icon Scatter"
            href: Hiplot/035-custom-icon-scatter.qmd
          - text: "D3 Wordcloud"
            href: Hiplot/036-d3-wordcloud.qmd
          - text: "Dendrogram"
            href: Hiplot/037-dendrogram.qmd
          - text: "Mirror Density & Histogram"
            href: Hiplot/038-density-hist-mirror.qmd
          - text: "Density-Histogram"
            href: Hiplot/039-density-histogram.qmd
          - text: "Density"
            href: Hiplot/040-density.qmd
          - text: "Deviation Plot"
            href: Hiplot/041-deviation-plot.qmd
          - text: "Diffusion Map"
            href: Hiplot/042-diffusion-map.qmd
          - text: "Diverging Scale"
            href: Hiplot/043-diverging-scale.qmd
          - text: "DIY GSEA"
            href: Hiplot/044-diy-gsea.qmd
          - text: "Donut"
            href: Hiplot/045-donut.qmd
          - text: "Dotchart"
            href: Hiplot/046-dotchart.qmd
          - text: "Dual Y Axis Chart"
            href: Hiplot/047-dual-y-axis.qmd
          - text: "Dumbbell Chart"
            href: Hiplot/048-dumbbell.qmd
          - text: "Easy Pairs"
            href: Hiplot/049-easy-pairs.qmd
          - text: "Easy SOM"
            href: Hiplot/050-easy-som.qmd
          - text: "Eulerr Plot"
            href: Hiplot/051-eulerr.qmd
          - text: "Extended Scatter"
            href: Hiplot/052-extended-scatter.qmd
          - text: "Cox Models Forest"
            href: Hiplot/053-ezcox.qmd
          - text: "Fan Plot"
            href: Hiplot/054-fan.qmd
          - text: "Fishplot"
            href: Hiplot/055-fishplot.qmd
          - text: "Flower plot"
            href: Hiplot/056-flowerplot.qmd
          - text: "Funnel Plot (metafor)"
            href: Hiplot/057-funnel-plot-metafor.qmd
          - text: "Funnel Plot"
            href: Hiplot/058-funnel-plot.qmd
          - text: "Gantt"
            href: Hiplot/059-gantt.qmd
          - text: "Gene Density"
            href: Hiplot/060-gene-density.qmd
          - text: "Gene Ranking Dotplot"
            href: Hiplot/061-gene-rank.qmd
          - text: "Gene Cluster Trend"
            href: Hiplot/062-gene-trend.qmd
          - text: "Barstats"
            href: Hiplot/063-ggbarstats.qmd
          - text: "Betweenstats"
            href: Hiplot/064-ggbetweenstats.qmd
          - text: "Directed Acyclic Graphs"
            href: Hiplot/065-ggdag.qmd
          - text: "Dist Plot"
            href: Hiplot/066-ggdist.qmd
          - text: "Histostats"
            href: Hiplot/067-gghistostats.qmd
          - text: "GGPIE"
            href: Hiplot/068-ggpie.qmd
          - text: "Piestats Group"
            href: Hiplot/069-ggpiestats-group.qmd
          - text: "Piestats"
            href: Hiplot/071-ggpiestats.qmd
          - text: "GGPubr Boxplot"
            href: Hiplot/072-ggpubr-boxplot.qmd
          - text: "Scatterstats"
            href: Hiplot/073-ggscatterstats.qmd
          - text: "Seqlogo"
            href: Hiplot/074-ggseqlogo.qmd
          - text: "Complex-Violin"
            href: Hiplot/075-ggwithinstats.qmd
          - text: "ggwordcloud"
            href: Hiplot/076-ggwordcloud.qmd
          - text: "GOBar Plot"
            href: Hiplot/077-gobar.qmd
          - text: "GOBubble Plot"
            href: Hiplot/078-gobubble.qmd
          - text: "GOCircle Plot"
            href: Hiplot/079-gocircle.qmd
          - text: "Group Rank Dotplot"
            href: Hiplot/080-grdotplot.qmd
          - text: "Group Bubble"
            href: Hiplot/081-group-bubble.qmd
          - text: "Group-comparison Heatmap"
            href: Hiplot/082-group-comparison.qmd
          - text: "Group Dumbbell"
            href: Hiplot/083-group-dumbbell.qmd
          - text: "Group Line"
            href: Hiplot/084-group-line.qmd
          - text: "Half Violin"
            href: Hiplot/085-half-violin.qmd
          - text: "Heatmap"
            href: Hiplot/086-heatmap.qmd
          - text: "Hi-C Heatmap"
            href: Hiplot/087-hic-heatmap.qmd
          - text: "Histogram"
            href: Hiplot/088-histogram.qmd
          - text: "Interval Area Chart"
            href: Hiplot/089-interval-area-chart.qmd
          - text: "Interval Bar Chart"
            href: Hiplot/090-interval-bar-chart.qmd
          - text: "Likert Plot"
            href: Hiplot/091-likert.qmd
          - text: "Line (Color Dot)"
            href: Hiplot/092-line-color-dot.qmd
          - text: "Line (errorbar)"
            href: Hiplot/093-line-errorbar.qmd
          - text: "Line Regression"
            href: Hiplot/094-line-regression.qmd
          - text: "Line"
            href: Hiplot/095-line.qmd
          - text: "Africa Map"
            href: Hiplot/096-map-africa.qmd
          - text: "Americas Map"
            href: Hiplot/097-map-americas.qmd
          - text: "China Map (City)"
            href: Hiplot/098-map-china-city.qmd
          - text: "China Map (County)"
            href: Hiplot/099-map-china-county.qmd
          - text: "China Map"
            href: Hiplot/100-map-china.qmd
          - text: "China Map 2"
            href: Hiplot/101-map-china2.qmd
          - text: "Europe Map"
            href: Hiplot/102-map-europe.qmd
          - text: "France Map (Town)"
            href: Hiplot/103-map-france-town.qmd
          - text: "France Map"
            href: Hiplot/104-map-france.qmd
          - text: "Germany Map (Town)"
            href: Hiplot/106-map-germany-town.qmd
          - text: "Germany Map"
            href: Hiplot/107-map-germany.qmd
          - text: "North America Map"
            href: Hiplot/108-map-north-america.qmd
          - text: "Oceania/Antarc Map"
            href: Hiplot/109-map-oceania-antarc.qmd
          - text: "South America Map"
            href: Hiplot/111-map-south-america.qmd
          - text: "Oceania/Antarc Map"
            href: Hiplot/112-map-uk-city.qmd
          - text: "South America Map"
            href: Hiplot/113-map-uk.qmd
          - text: "Oceania/Antarc Map"
            href: Hiplot/114-map-usa-county.qmd
          - text: "USA Map (States)"
            href: Hiplot/115-map-usa.qmd
          - text: "World Map"
            href: Hiplot/116-map-world.qmd
          - text: "World Map 2"
            href: Hiplot/117-map-world2.qmd
          - text: "Matrix Bubble"
            href: Hiplot/118-matrix-bubble.qmd
          - text: "Meta-analysis of Binary Data"
            href: Hiplot/119-meta-bin.qmd
          - text: "Meta-analysis of Continuous Data"
            href: Hiplot/120-meta-cont.qmd
          - text: "Meta-Subgroup Analysis"
            href: Hiplot/121-metawho.qmd
          - text: "Moon charts"
            href: Hiplot/122-moon-charts.qmd
          - text: "Mosaic Ratio Plot"
            href: Hiplot/123-mosaic.qmd
          - text: "Multiple Histograms"
            href: Hiplot/125-multiple-histograms.qmd
          - text: "Network (igraph)"
            href: Hiplot/127-network-igraph.qmd
          - text: "Neural Network"
            href: Hiplot/129-neural-network.qmd
          - text: "Nomogram (Logistic)"
            href: Hiplot/130-nomogram-logistic.qmd
          - text: "Nomogram"
            href: Hiplot/131-nomogram.qmd
          - text: "Parallel Coordinate"
            href: Hiplot/132-parallel-coordinate.qmd
          - text: "Pareto Chart"
            href: Hiplot/133-pareto-chart.qmd
          - text: "Parliament"
            href: Hiplot/134-parliament.qmd
          - text: "PCA2"
            href: Hiplot/135-pca2.qmd
          - text: "PCAtools"
            href: Hiplot/136-pcatools.qmd
          - text: "Perspective"
            href: Hiplot/137-perspective.qmd
          - text: "PCAtools"
            href: Hiplot/138-pie-3d.qmd
          - text: "Pie Group"
            href: Hiplot/139-pie-group.qmd
          - text: "Pie Matrix"
            href: Hiplot/140-pie-matrix.qmd
          - text: "Pie"
            href: Hiplot/141-pie.qmd
          - text: "Point (SD)"
            href: Hiplot/142-point-sd.qmd
          - text: "EnhancedMA"
            href: Hiplot/143-pseudo-enhanced-ma.qmd
          - text: "Pyramid Chart"
            href: Hiplot/144-pyramid-chart.qmd
          - text: "Pyramid Chart 2"
            href: Hiplot/145-pyramid-chart2.qmd
          - text: "Pyramid Stack"
            href: Hiplot/146-pyramid-stack.qmd
          - text: "Pyramid Stack2"
            href: Hiplot/147-pyramid-stack2.qmd
          - text: "QQ Plot"
            href: Hiplot/148-qqplot.qmd
          - text: "R Script Flow"
            href: Hiplot/149-r-code-flow.qmd
          - text: "Radar"
            href: Hiplot/150-radar.qmd
          - text: "RCS-COX"
            href: Hiplot/151-rcs-cox.qmd
          - text: "RCS-LRM"
            href: Hiplot/152-rcs-lrm.qmd
          - text: "Ribbon"
            href: Hiplot/153-ribbon.qmd
          - text: "Ridge"
            href: Hiplot/154-ridge.qmd
          - text: "Risk Factor Analysis"
            href: Hiplot/155-risk-plot.qmd
          - text: "ROC"
            href: Hiplot/156-roc.qmd
          - text: "Rose Chart"
            href: Hiplot/157-rose-chart.qmd
          - text: "Sankey"
            href: Hiplot/158-sankey.qmd
          - text: "3D-Scatter"
            href: Hiplot/159-scatter-3d.qmd
          - text: "Gradient Scatter"
            href: Hiplot/160-scatter-gradient.qmd
          - text: "Scatter"
            href: Hiplot/161-scatter.qmd
          - text: "Scatter2"
            href: Hiplot/162-scatter2.qmd
          - text: "Scatterpie"
            href: Hiplot/163-scatterpie.qmd
          - text: "Simple Funnel Diagram"
            href: Hiplot/164-simple-funnel-diagram.qmd
          - text: "Slopegraph"
            href: Hiplot/165-slopegraph.qmd
          - text: "Simple Funnel Diagram"
            href: Hiplot/166-stack-violin.qmd
          - text: "Percentsge Stacked Bar Chart"
            href: Hiplot/167-stacked-percentage-bar-chart.qmd
          - text: "Streamgraph"
            href: Hiplot/168-streamgraph.qmd
          - text: "Survival Analysis"
            href: Hiplot/169-survival.qmd
          - text: "Taylor Diagram"
            href: Hiplot/170-taylor-diagram.qmd
          - text: "Time ROC"
            href: Hiplot/171-time-roc.qmd
          - text: "Treeheatr"
            href: Hiplot/172-treeheatr.qmd
          - text: "Treemap"
            href: Hiplot/173-treemap.qmd
          - text: "Tricolor Histogram"
            href: Hiplot/174-tricolor-histogram.qmd
          - text: "tSNE"
            href: Hiplot/175-tsne.qmd
          - text: "UMAP"
            href: Hiplot/176-umap.qmd
          - text: "Upset Plot"
            href: Hiplot/177-upset-plot.qmd
          - text: "Venn"
            href: Hiplot/178-venn.qmd
          - text: "Venn2"
            href: Hiplot/179-venn2.qmd
          - text: "Violin Group"
            href: Hiplot/180-violin-group.qmd
          - text: "Violin"
            href: Hiplot/181-violin.qmd
          - text: "Visdat"
            href: Hiplot/182-visdat.qmd
          - text: "Volcano"
            href: Hiplot/183-volcano.qmd
          - text: "Waffle Plot"
            href: Hiplot/184-waffle.qmd
          - text: "Waterfalls Plot2"
            href: Hiplot/185-waterfalls-plot.qmd
          - text: "Waterfalls"
            href: Hiplot/186-waterfalls.qmd
          - text: "PCA"
            href: Hiplot/187-pca.qmd

      - text: "About Us"
        href: About.qmd


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto
  
  
comments:
  giscus:
    repo: "openbiox/Bizard"
    repo-id: "R_kgDONWVY7Q"
    category: "Announcements"
    category-id: "DIC_kwDONWVY7c4ClcJT"
    mapping: "pathname"
    reactions-enabled: true
    input-position: "top"
    theme: "preferred_color_scheme"
    loading: "lazy"

babelquarto:
  languagelinks: sidebar
  languagecodes:
  - name: zh
    text: "中文"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['zh']
title-es: "English"
title-zh: "中文"
lang: en
