project: 
  type: website
  output-dir: _site
  execute-dir: project

website: 
  favicon: images/favicon.ico
  page-navigation: true
  title: "A Biomedical Visualization Atlas" 
  site-url: "https://openbiox.github.io/Bizard/" 
  repo-url: https://github.com/openbiox/Bizard
  repo-actions:
    - source
    - issue

  page-footer:
    left: "&copy; CC-By Peng Lab, 2024-2025. All rights reserved."
    right: "This page is built with [Quarto](https://quarto.org/)."
    center: |
      <a href='https://clustrmaps.com/site/1c4xe'  title='Visit tracker'><img src='//clustrmaps.com/map_v2.png?cl=ffffff&w=a&t=n&d=VK6_Uhjas4vA0CDps3EFeB0Fotb8hU50SYT4Fcq5nUI&co=91c5eb&ct=000000'/></a>
    
  sidebar:
    logo: "images/Bizard_logo.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/openbiox/Bizard
        text: "Bizard GitHub website"
      - icon: twitter
        href: https://x.com/PengL_Robin
        text: "Peng Lab Twitter"
      - icon: translate       

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "Graph Gallery"
        href: GraphGallery.qmd
      - section: "𝐁𝐀𝐒𝐈𝐂𝐒"
      - section: "Distribution"
        contents: 
          - text: "Violin Plot"
            href: Distribution/ViolinPlot.qmd
          - text: "Density Plot"
            href: Distribution/Density.qmd
          - text: "Histogram"
            href: Distribution/Histogram.qmd
          - text: "Box Plot"
            href: Distribution/BoxPlot.qmd
          - text: "Ridgeline Plot"
            href: Distribution/Ridgeline.qmd
          - text: "Beeswarm Plot"
            href: Distribution/Beeswarm.qmd
      - section: "Correlation"
        contents: 
          - text: "Scatter Plot"
            href: Correlation/Scatter.qmd
          - text: "Heatmap"
            href: Correlation/Heatmap.qmd
          - text: "Correlogram"
            href: Correlation/Correlogram.qmd
          - text: "Bubble Plot"
            href: Correlation/Bubble.qmd
          - text: "Connected Scatter"
            href: Correlation/ConnectedScatter.qmd
          - text: "2D Density"
            href: Correlation/Density2D.qmd
      - section: "Ranking"
        contents: 
          - text: "Bar Plot"
            href: Ranking/BarPlot.qmd
          - text: "Radar/Spider Chart"
            href: Ranking/Radar.qmd
          - text: "Wordcloud"
            href: Ranking/Wordcloud.qmd
          - text: "Parallel Coordinates Plot"
            href: Ranking/Parallel.qmd
          - text: "Lollipop Plot"
            href: Ranking/Lollipop.qmd
          - text: "Circular Barplot"
            href: Ranking/CircularBarplot.qmd
          - text: "Table"
            href: Ranking/Table.qmd
          - text: "VeenPlot"
            href: Ranking/VennPlot.qmd
          - text: "UpsetPlot"
            href: Ranking/UpsetPlot.qmd
      - section: "Composition/Part Of The Whole"
        contents: 
          - text: "Grouped and Stacked Barplot"
            href: Composition/GroupedBarplot.qmd
          - text: "Treemap"
            href: Composition/Treemap.qmd
          - text: "Donut Chart"
            href: Composition/Donut.qmd
          - text: "Pie Chart"
            href: Composition/PieChart.qmd
          - text: "Dendrogram"
            href: Composition/Dendrogram.qmd
          - text: "Circular Packing Chart"
            href: Composition/CircularPacking.qmd
          - text: "Waffle Chart"
            href: Composition/Waffle.qmd
      - section: "Data Over Time/Evolution"
        contents: 
          - text: "Line Chart"
            href: DataOverTime/LineChart.qmd
          - text: "Area Chart"
            href: DataOverTime/AreaChart.qmd
          - text: "Stacked Area Chart"
            href: DataOverTime/StackedArea.qmd
          - text: "Streamgraph"
            href: DataOverTime/Streamgraph.qmd
          - text: "Timeseries"
            href: DataOverTime/Timeseries.qmd
      - section: "Proportion/Flow"
        contents: 
          - text: "Chord Diagram"
            href: Proportion/ChordDiagram.qmd
          - text: "Network Graph"
            href: Proportion/Network.qmd
          - text: "Sankey Diagram"
            href: Proportion/Sankey.qmd
          - text: "Arc Diagram"
            href: Proportion/ArcDiagram.qmd
          - text: "Hierarchical Edge Bundling"
            href: Proportion/EdgeBundling.qmd
      - section: "Animation"
        contents: 
          - text: "Animation"
            href: Animation/Animation.qmd
          - text: "Interactivity"
            href: Animation/Interactivity.qmd
      - section: "𝐎𝐌𝐈𝐂𝐒"
      - section: "𝐂𝐋𝐈𝐍𝐈𝐂𝐒"
      
      - section: "HIPLOT"
        contents: 
          - text: "Area"
            href: Hiplot/001-area.qmd
          - text: "Barcode Plot"
            href: Hiplot/002-barcode-plot.qmd
          - text: "3D Barplot"
            href: Hiplot/003-barplot-3d.qmd
          - text: "Barplot Color Group"
            href: Hiplot/004-barplot-color-group.qmd
          - text: "Barplot (errorbar)"
            href: Hiplot/005-barplot-errorbar.qmd
          - text: "Barplot (errorbar2)"
            href: Hiplot/006-barplot-errorbar2.qmd
          - text: "Barplot Gradient"
            href: Hiplot/008-barplot-gradient.qmd
          - text: "Multiple Barplot&Line"
            href: Hiplot/009-barplot-line-multiple.qmd
          - text: "Barplot"
            href: Hiplot/010-barplot.qmd
          - text: "Beanplot"
            href: Hiplot/011-beanplot.qmd
          - text: "Beeswarm"
            href: Hiplot/012-beeswarm.qmd
          - text: "Corrplot Big Data"
            href: Hiplot/013-big-corrplot.qmd
          - text: "Bivariate Chart"
            href: Hiplot/014-bivariate.qmd   
          - text: "Boxplot"
            href: Hiplot/015-boxplot.qmd
          - text: "Bubble"
            href: Hiplot/016-bubble.qmd
          - text: "Bumpchart"
            href: Hiplot/017-bumpchart.qmd
          - text: "Calibration Curve"
            href: Hiplot/018-calibration-curve.qmd
          - text: "Chi-square-fisher Test"
            href: Hiplot/019-chi-square-fisher.qmd
          - text: "Chord Plot"
            href: Hiplot/020-chord.qmd
          - text: "Circle Packing"
            href: Hiplot/021-circle-packing.qmd
          - text: "Circular Barplot"
            href: Hiplot/023-circular-barplot.qmd
          - text: "Circular Pie Chart"
            href: Hiplot/024-circular-pie-chart.qmd
          - text: "Complex Heatmap"
            href: Hiplot/025-complex-heatmap.qmd
          - text: "Connected Scatterplot"
            href: Hiplot/026-connected-scatterplot.qmd
          - text: "Contour (Matrix)"
            href: Hiplot/027-contour-matrix.qmd
          - text: "Contour (XY)"
            href: Hiplot/028-contour-xy.qmd
          - text: "Simplified Correlation Heatmap"
            href: Hiplot/029-cor-heatmap-simple.qmd
          - text: "Correlation Heatmap"
            href: Hiplot/030-cor-heatmap.qmd
          - text: "Group Bubble"
            href: Hiplot/081-group-bubble.qmd
          - text: "Group-comparison Heatmap"
            href: Hiplot/082-group-comparison.qmd
          - text: "Group Dumbbell"
            href: Hiplot/083-group-dumbbell.qmd
          - text: "Group Line"
            href: Hiplot/084-group-line.qmd
          - text: "Half Violin"
            href: Hiplot/085-half-violin.qmd
          - text: "Heatmap"
            href: Hiplot/086-heatmap.qmd
          - text: "Hi-C Heatmap"
            href: Hiplot/087-hic-heatmap.qmd
          - text: "Histogram"
            href: Hiplot/088-histogram.qmd
          - text: "Interval Area Chart"
            href: Hiplot/089-interval-area-chart.qmd
          - text: "Interval Bar Chart"
            href: Hiplot/090-interval-bar-chart.qmd
      
      - text: "About Us"
        href: About.qmd
        

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto
  
  
comments:
  giscus:
    repo: "openbiox/Bizard"
    repo-id: "R_kgDONWVY7Q"
    category: "Announcements"
    category-id: "DIC_kwDONWVY7c4ClcJT"
    mapping: "pathname"
    reactions-enabled: true
    input-position: "top"
    theme: "preferred_color_scheme"
    loading: "lazy"

babelquarto:
  languagelinks: sidebar
  languagecodes:
  - name: zh
    text: "中文"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['zh']
title-es: "English"
title-zh: "中文"
lang: en
